[hololens]
package = "holo/lens-sencha-package"

[hololens.sencha]
pkg = "slate-assets"

[hololens.input]
root = "sencha-workspace"
files = [
    "packages/slate-assets/**",
    "ext/**",
    "workspace.json",
]

[hololens.output]
root = "webapp-plugin-builds/slate-assets"
merge = "replace"